sudo: required
services:
  - docker

before_install:
  - docker build -t shivamrawat101/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shivamrawat101/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-app"
  env: "Docker-app-env"
  bucket_name: "elasticbeanstalk-eu-north-1-211125684662"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
