sudo: required
services:
  - docker

before_install:
  - docker build -t shivamrawat101/docker-react -f Dockerfile.dev .

script:
  - docker run shivamrawat101/docker-react npm run test -- --coverage
